### ISSUE TITLE
Call for mentors for Coding Grace event

### ISSUE THREAD

**Issue by francesmcmullin** [nodeschool/dublin#3]
Hey @nodeschool/dublin !

I'm helping to run a JavaScript workshop for Coding Grace on Saturday April 18th. I decided working through nodeschool exercises would be a good way for people to learn and leave a clear path for continued learning. If anyone is free on the day, we'd love to get some more mentors.

http://www.codinggrace.com/events/dive-javascript/44/

Thanks,

David.

**Comment by No9** [comment]
Have commitments on the 19th so doing Saturday as well will be tricky
Will let you know either way by the end of the week.
